// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oppimistehtävä_5.DataBaseContext;

namespace Oppimistehtävä_5.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Oppimistehtävä_5.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Oppimistehtävä_5.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Ordered")
                        .HasColumnType("TEXT");

                    b.Property<int?>("customerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("customerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Oppimistehtävä_5.Models.OrderRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Discount")
                        .HasColumnType("REAL");

                    b.Property<int?>("orderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("productId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.ToTable("OrderRows");
                });

            modelBuilder.Entity("Oppimistehtävä_5.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Oppimistehtävä_5.Models.Order", b =>
                {
                    b.HasOne("Oppimistehtävä_5.Models.Customer", "customer")
                        .WithMany("Orders")
                        .HasForeignKey("customerId");
                });

            modelBuilder.Entity("Oppimistehtävä_5.Models.OrderRow", b =>
                {
                    b.HasOne("Oppimistehtävä_5.Models.Order", "order")
                        .WithMany("orderRows")
                        .HasForeignKey("orderId");

                    b.HasOne("Oppimistehtävä_5.Models.Product", "product")
                        .WithMany("orderRows")
                        .HasForeignKey("productId");
                });
#pragma warning restore 612, 618
        }
    }
}
